steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/mlops/train:latest',
    '-f',
    'train_cloud.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/mlops/train:latest'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
