steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image train'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/mlops/train:latest',
    '-f',
    'train_cloud.dockerfile'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image train'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/mlops/train:latest'
  ]
  waitFor: ['Build container image train']
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image api'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/mlops/api:latest',
    '-f',
    'api_cloud.dockerfile'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image api'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/mlops/api:latest'
  ]
  waitFor: ['Build container image api']
options:
  logging: CLOUD_LOGGING_ONLY
