# CPU since google is blocking us from using GPUs
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/mlops/train.dockerfile
