# CPU since google is blocking us from using GPUs
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: europe-west3-docker.pkg.dev/agile-scheme-448123-f3/mlops/train:latest
        command:
          - python
        args:
          - src/mlops/train.py
          - experiment.n_epochs=1
          - experiment.model_path=/gcs/pistachio_data_train/models/model_test.ckpt
          - experiment.dataset_path=/gcs/pistachio_data_train/data/processed/Pistachio_Image_Dataset/Pistachio_Image_Dataset
